import dotenv from 'dotenv';
dotenv.config();

export const CONFIG = {
  RPC_URL: process.env.RPC_URL,
  PRIVATE_KEY: process.env.PRIVATE_KEY,
  STATEKEEPER_ADDRESS: process.env.STATEKEEPER_ADDRESS,
  REGISTRATION2_ADDRESS: process.env.REGISTRATION2_ADDRESS,
  CERTIFICATES_SMT_ADDRESS: process.env.CERTIFICATES_SMT_ADDRESS,
  STATEKEEPER_ABI_PATH: process.env.STATEKEEPER_ABI_PATH,
  REGISTRATION2_ABI_PATH: process.env.REGISTRATION2_ABI_PATH,
  QUERY_PROOF_EXECUTOR_ADDRESS: process.env.QUERY_PROOF_EXECUTOR_ADDRESS,
  QUERY_PROOF_EXECUTOR_ABI_PATH: process.env.QUERY_PROOF_EXECUTOR_ABI_PATH,
};
